### ISSUE TITLE
Email Sendungsverfolgung

### ISSUE THREAD

**Issue by webregie** [OXIDprojects/carrier_tracking#4]
Wie bekomme ich in die Email die Sendungsverfolgung für diese individuellen Carrier?

Großes Lob an das Modul. Auf der Seite funktioniert es auch in einer OXID 4.9.6

**Comment by kermie** [comment]
Am besten über's Forum anfragen ;)

**Comment by webregie** [comment]
Habe ich längst getan. Hoffe da kommt was: 
http://forum.oxid-esales.com/showthread.php?s=5a48efbc9908d786a820606d68cec781&t=22800&page=2#post176873
